/**
 * M9.1's own "Assets" section asks for AVIF + WebP + JPEG fallback at 1920w/1280w/960w,
 * generated by a build step, served via `<picture>`/`srcset`. That image pipeline is
 * explicitly step 5 of the brief's own "Order of work" — after the lead developer has
 * calibrated the real photographs — so for now this serves the single placeholder source
 * file directly, no resizing or format negotiation yet. Kept as its own module (rather than
 * inlined in StationCockpit.tsx) so swapping in the real pipeline later touches one file.
 */
export function stationImageFallback(imageBase: string): string {
  return `/stations/${imageBase}.jpg`;
}

/** `undefined` until the real multi-width pipeline exists — `<img srcSet>` with one entry is
 *  pointless, so StationCockpit.tsx omits the attribute entirely rather than passing an empty
 *  string. */
export function stationImageSrcSet(_imageBase: string): string | undefined {
  return undefined;
}
