/**
 * M9.7: the mobile Playwright pass against the brief's own M9 done-when bar ("30+ FPS in the
 * Lighthouse mobile profile, low-power mode works, reduced motion honored"). Lighthouse itself
 * (scripts/lighthouse.ts) formalizes the Performance-score/Total-Blocking-Time half of that
 * bar, since Lighthouse has no literal FPS metric — this file supplies the actual rendered-
 * frames-per-second number Lighthouse doesn't produce, plus the low-power/reduced-motion
 * checks that need a real animation actually running (or not) to mean anything.
 *
 * CPU-throttled via CDP (Emulation.setCPUThrottlingRate), the same technique Lighthouse's own
 * mobile profile uses (a 4x slowdown) — without it, this would measure the test runner's own
 * desktop-class CPU, not "a low-end Android phone" (CLAUDE.md rule 6), and the number would be
 * meaningless for that comparison.
 */
import { expect, test, type Page } from "@playwright/test";
import { gotoApp, openTab } from "./fixtures.js";

const CPU_THROTTLE_RATE = 4;
const MEASURE_MS = 1000;
const MIN_FPS = 30;

async function throttleCpu(page: Page): Promise<void> {
  const client = await page.context().newCDPSession(page);
  await client.send("Emulation.setCPUThrottlingRate", { rate: CPU_THROTTLE_RATE });
}

/** Counts real `requestAnimationFrame` callbacks over `ms` — the browser's own paint loop,
 *  not a simulated number, so whatever CSS animation or React re-render cost is actually on
 *  screen counts against it. */
async function measureFps(page: Page, ms: number): Promise<number> {
  return page.evaluate(
    (duration) =>
      new Promise<number>((resolve) => {
        let frames = 0;
        const start = performance.now();
        function tick() {
          frames++;
          if (performance.now() - start < duration) {
            requestAnimationFrame(tick);
          } else {
            resolve(Math.round((frames * 1000) / duration));
          }
        }
        requestAnimationFrame(tick);
      }),
    ms,
  );
}

test.describe("Mobile performance (M9.7)", () => {
  test("Habitat view sustains 30+ FPS on a throttled CPU while idle", async ({ page }) => {
    await gotoApp(page);
    await throttleCpu(page);
    for (let i = 0; i < 7; i++) await page.getByRole("button", { name: "Next" }).click();
    await page.getByRole("button", { name: "Launch Mission" }).click();
    await openTab(page, "Habitat");
    await expect(page.getByRole("heading", { name: "Habitat", exact: true })).toBeVisible();

    const fps = await measureFps(page, MEASURE_MS);
    expect(fps).toBeGreaterThanOrEqual(MIN_FPS);
  });

  test("the establishing shot's transit animation sustains 30+ FPS while actually playing, on a throttled CPU", async ({
    page,
  }) => {
    await gotoApp(page);
    await throttleCpu(page);
    for (let i = 0; i < 4; i++) await page.getByRole("button", { name: "Next" }).click();
    await expect(page.getByText("Step 5 of 8: Transit")).toBeVisible();
    await expect(page.locator(".establishing-shot-craft")).toBeVisible();

    // Sampled mid-animation (the transit runs 4s) — the point at which frames are actually
    // being generated by the keyframe, not before it starts or after it's finished.
    const fps = await measureFps(page, MEASURE_MS);
    expect(fps).toBeGreaterThanOrEqual(MIN_FPS);
  });

  test("low-power mode measurably reduces work: the transit animation genuinely stops producing frames of its own", async ({
    page,
  }) => {
    await gotoApp(page);
    await page.getByRole("button", { name: "Low-power mode" }).click();
    for (let i = 0; i < 4; i++) await page.getByRole("button", { name: "Next" }).click();
    await expect(page.getByText("Step 5 of 8: Transit")).toBeVisible();

    const craft = page.locator(".establishing-shot-craft");
    const transform = await craft.evaluate((el) => getComputedStyle(el).transform);
    await page.waitForTimeout(600);
    const transformLater = await craft.evaluate((el) => getComputedStyle(el).transform);
    // With the animation genuinely stopped, the craft's own transform is frozen at its end
    // state — unlike the running case, it does not keep changing between two samples.
    expect(transform).toBe(transformLater);
  });

  test("the OS's own prefers-reduced-motion is honoured, independent of the manual toggle", async ({
    page,
  }) => {
    await page.emulateMedia({ reducedMotion: "reduce" });
    await gotoApp(page);
    for (let i = 0; i < 4; i++) await page.getByRole("button", { name: "Next" }).click();
    await expect(page.getByText("Step 5 of 8: Transit")).toBeVisible();

    const craft = page.locator(".establishing-shot-craft");
    const animationName = await craft.evaluate((el) => getComputedStyle(el).animationName);
    expect(animationName).toBe("none");
  });

  // M9.1's own performance rule: "30+ FPS on low-end Android; if cockpit image regresses
  // Lighthouse mobile, cockpit stays desktop-only" — the same throttled-CPU technique as the
  // Habitat/establishing-shot checks above, now against the real calibrated cockpit frame
  // (all ten stations have one — screenMaps.ts) rather than the Classic console underneath it.
  test("Life Support cockpit view sustains 30+ FPS on a throttled CPU while idle", async ({
    page,
  }) => {
    await gotoApp(page);
    await openTab(page, "Mission Command");
    await page.getByRole("button", { name: /^First Light/ }).click();
    await openTab(page, "Life Support");
    await throttleCpu(page);
    await expect(page.locator(".cockpit-frame")).toBeVisible();

    const fps = await measureFps(page, MEASURE_MS);
    expect(fps).toBeGreaterThanOrEqual(MIN_FPS);
  });
});
