/**
 * Regenerates docs/BALANCE.md from the same harness validation/balance.test.ts asserts
 * against (packages/sim/src/engine/balance.ts), so the committed doc can never drift from
 * what CI actually checks. Run locally by the lead developer after any change that could
 * move the pass-rate distribution — a new incident, a retuned constant, a rebalanced bot.
 *
 * Usage:
 *   pnpm --filter @sol-keeper/sim run build   # this script runs against the built package
 *   node scripts/generate-balance-doc.ts
 */
import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
// A relative import to the built package, not the bare "@sol-keeper/sim" specifier: the
// package is only declared as a dependency of apps/web (workspace:*), and Node's ESM
// resolution for a bare specifier walks up from *this file's* location, not from the
// working directory a script happens to be run from — scripts/ itself has no node_modules
// entry for it. Still "the built package, not a source alias" (CLAUDE.md), just addressed
// directly rather than through a specifier only apps/web can resolve.
import {
  runCombination,
  decisionCoverage,
  idleBot,
  worstChoiceBot,
  greedyBot,
  prudentBot,
  type Bot,
  type MissionDifficulty,
  type ScenarioId,
} from "../packages/sim/dist/index.js";

const SEEDS = 150;
const SCENARIOS: readonly ScenarioId[] = ["jezero-outpost", "first-light", "the-long-night"];
const DIFFICULTIES: readonly MissionDifficulty[] = ["training", "nominal", "flightRated"];
const BOTS: readonly Bot[] = [idleBot, worstChoiceBot, greedyBot, prudentBot];

const OUT_PATH = fileURLToPath(new URL("../docs/BALANCE.md", import.meta.url));

function pct(x: number): string {
  return `${(x * 100).toFixed(1)}%`;
}

async function main(): Promise<void> {
  const rows: string[] = [];
  const allCauses = new Set<string>();
  const coverageSections: string[] = [];
  const t0 = Date.now();

  for (const scenarioId of SCENARIOS) {
    for (const difficulty of DIFFICULTIES) {
      for (const bot of BOTS) {
        const result = runCombination(scenarioId, difficulty, bot, SEEDS);
        for (const cause of result.causesSeen) allCauses.add(cause);
        const c = result.statusCounts;
        rows.push(
          `| ${scenarioId} | ${difficulty} | ${bot.id} | ${pct(result.successRate)} | ${c.success} | ${c.partial} | ${c.abort} | ${c.loss} | ${[...result.causesSeen].join(", ") || "—"} |`,
        );
      }
    }

    // M7.6 Part C.7: aggregated across all difficulties and bots for this scenario, so the
    // table stays a readable size — how often each incident response was ever chosen and the
    // fraction of runs that chose it that went on to succeed.
    const coverage = decisionCoverage(scenarioId, DIFFICULTIES, BOTS, SEEDS);
    const coverageRows = coverage
      .map((e) => `| ${e.incidentId} | ${e.responseId} | ${e.timesChosen} | ${pct(e.successRateWhenChosen)} |`)
      .join("\n");
    coverageSections.push(`### ${scenarioId}\n\n| Incident | Response | Times chosen | Success rate when chosen |\n|---|---|---|---|\n${coverageRows}`);
  }

  const md = `# Balance report

Generated by \`scripts/generate-balance-doc.ts\` from \`packages/sim/src/engine/balance.ts\` —
the same harness \`validation/balance.test.ts\` asserts the brief's pass/fail targets against
(docs/PHASE2_BRIEF.md, "Balance harness"). This file is generated output, never hand-edited:
regenerate it after any change that could move the distribution below, rather than editing
the numbers directly.

${SEEDS} seeds per row, computed in ${Date.now() - t0} ms.

## Brief targets

- idleBot success: <=5% (Nominal, Flight-Rated), <=30% (Training)
- prudentBot success: >=85% Training, >=70% Nominal, 40-60% Flight-Rated
- greedyBot: strictly between idleBot and prudentBot
- Every failure mode reachable in at least one idleBot or greedyBot seed

**Known gap** (tracked in validation/balance.test.ts, not silently dropped — see that test
file's header comment for the full diagnosis): Jezero and The Long Night's prudentBot clears
every floor above but sits well past the Flight-Rated *upper* bound (its strategy neutralises
most incidents it responds to well enough that raising Flight-Rated's incident rate further
would only punish idleBot/greedyBot, not a skilled bot). First Light's own prudentBot/idleBot
gap (\`depress-mir97\`'s fast kill clock outrunning a 2-person crew's only unassigned-station
responder) is resolved — see \`management.secondResponderPerformanceBonusFraction\`.

**ABORT is now reachable** (M9-prep audit): the mechanism (\`engine/outcome.ts\`'s
\`shouldConsiderAbort\`/\`requestAbort\`) existed since M7.7 but no bot ever called it — this
file's own outcome table previously showed 0 aborts across every one of 4,050 seeds, a real
credibility risk for a built-and-documented-but-never-exercised feature. prudentBot now
leaves the moment its dose or a sustained-critical-with-no-repair-path signal fires;
greedyBot reacts to the same crew-critical signal only, matching the brief's own "greedyBot
aborts too late"; idleBot still never does. Both are gated against aborting when the mission's
own natural end is closer than the abort's own cost (the Moon's ~144 h return transit) —
without that gate, a seed-level diagnostic found prudentBot/greedyBot converting several
First Light Training seeds that would have reached a natural SUCCESS into an unneeded
abort-PARTIAL in the mission's final ~20 hours (see \`engine/bots.ts\`'s own comments). ABORT
is genuinely rare with today's thresholds: 4-5 of 150 seeds on The Long Night per difficulty
(see the outcome table below), and only reachable on Jezero/First Light via a much wider seed
search (validation/balance.test.ts's own "ABORT is reachable, not just built" tests use the
specific seeds that search found, kept fast and deterministic rather than re-searching on
every CI run).

## Known limitations

Disclosed rather than silently left implicit — none of these are being chased right now
because fixing them would move balance numbers broadly, three days before M9, without the
seed-level verification that deserves.

1. **Crew-hours are only half the scarcity mechanism M7.7 §1 asked for.** The pooled daily
   budget (\`engine/crewHours.ts\`) is real and correctly deducted for incident responses and
   ordinary repairs, with genuine next-sol slippage visible in the Black Box. But farming,
   science, cleaning, and ISRU are not metered against it at all — those models have no
   \`crewHoursCost\` concept today. This is the single largest remaining gap in "no free
   labour anywhere," ranked here above the others because it is the scarcity mechanism the
   brief named explicitly and only got partially built.
2. **\`componentRiskBaseChancePerHour\` is 0.0045/h — a 222-hour MTBF no flight hardware
   resembles.** M7.5 §5 asked for this to be reframed as a TRL- and wear-scaled MTBF in the
   realistic 2,000-20,000 h band; it never was. It stands, named, as a \`"tuned"\` gameplay
   constant pending that rework, not a silently-accepted measured figure.
3. **\`shouldConsiderAbort\`'s consumables-shortfall signal is a naive burn-down projection.**
   It compares today's stock at today's ration rate against the mission's *full* remaining
   duration, with no awareness that rationing tightens over time or that crop harvests
   replenish food later in the mission — on a long, rationing-dependent scenario it can fire on
   hour 1 at nominal rations before a bot has had any chance to react. Excluded from the bots'
   own abort logic for exactly this reason (\`engine/bots.ts\`'s own comments). Fixing the
   projection itself — accounting for planned rationing and expected harvests — is real engine
   work, out of scope for this pass.
4. **ABORT has no player-facing control at all yet.** M7.7 §6 asks for it to be "exposed as a
   Mission Command decision whenever [the criteria] are met" — today \`requestAbort\`/
   \`shouldConsiderAbort\` are engine-only (\`engine/outcome.ts\`); no console, button, or
   Decision Card in \`apps/web\` calls either one. A human player cannot abort a mission today,
   only the bots can. This is a real M8 gap, not an M7 one — surfacing it belongs with M8's
   Mission Command console work, not this pass.

## Outcome distribution

| Scenario | Difficulty | Bot | Success | success | partial | abort | loss | Causes seen |
|---|---|---|---|---|---|---|---|---|
${rows.join("\n")}

## Failure causes observed across every idleBot/greedyBot seed

${[...allCauses].sort().map((c) => `- \`${c}\``).join("\n")}

## Decision coverage (M7.6 Part C.7)

For each incident, how often every bot combined ever chose each response (across all three
difficulties, ${SEEDS} seeds each) and the fraction of those runs that went on to SUCCEED.
Correlation, not causation — a response chosen only in already-favourable runs would read
high without being the reason why (see \`DecisionCoverageEntry\`'s own doc comment,
packages/sim/src/engine/balance.ts) — read alongside the outcome table above, not in place
of it.

${coverageSections.join("\n\n")}
`;

  await writeFile(OUT_PATH, md, "utf8");
  console.log(`Wrote ${OUT_PATH}`);
}

await main();
