/**
 * M9.1's own "Assets" section: AVIF + WebP + JPEG at 1920w/1280w/960w, generated by a build
 * step, served via `<picture>`/`srcset`, under 250KB target for the 1280w AVIF. This is a
 * local-only tool (CLAUDE.md's own `scripts/` convention — "run by the lead developer"), not
 * wired into `apps/web`'s own Vercel build: station photos change rarely, sharp is a native
 * binary not worth adding to the deploy path for that, and the derived files are committed
 * as ordinary static assets, re-run by hand (`pnpm gen:station-images`) whenever a station
 * photo is replaced or added.
 *
 * Reads every `*.jpg`/`*.png` in `apps/web/stations-src/` (deliberately **not**
 * `apps/web/public/`: the raw sources here run 1.7-2.3MB each, and vite-plugin-pwa's service
 * worker precache step hard-fails the production build the moment any precached asset exceeds
 * its 2MB default — confirmed directly, not a hypothetical — so the sources that only this
 * script ever reads must never land under `public/` where both Vite's static-copy and the PWA
 * precache would otherwise pick them up) and writes `<base>-<width>w.<ext>` siblings, for each
 * of WIDTHS × FORMATS, into `apps/web/public/stations/` — the one directory the app itself
 * references. `withoutEnlargement: true` (sharp's own option) means a source narrower than a
 * given width is left at its own native width instead of being blown up.
 *
 * Usage:
 *   pnpm gen:station-images
 */
import { readdir } from "node:fs/promises";
import { join, basename, extname } from "node:path";
import sharp, { type Sharp } from "sharp";

const SOURCE_DIR = join(process.cwd(), "apps/web/stations-src");
const OUTPUT_DIR = join(process.cwd(), "apps/web/public/stations");
const WIDTHS = [1920, 1280, 960] as const;
const FORMATS = ["avif", "webp", "jpg"] as const;
const AVIF_1280W_BUDGET_BYTES = 250 * 1024;

async function encode(image: Sharp, format: (typeof FORMATS)[number]): Promise<Buffer> {
  if (format === "avif") return image.avif({ quality: 55 }).toBuffer();
  if (format === "webp") return image.webp({ quality: 75 }).toBuffer();
  return image.jpeg({ quality: 80, mozjpeg: true }).toBuffer();
}

async function main(): Promise<void> {
  const entries = await readdir(SOURCE_DIR, { withFileTypes: true });
  const sources = entries.filter(
    (e) => e.isFile() && [".jpg", ".jpeg", ".png"].includes(extname(e.name).toLowerCase()),
  );

  if (sources.length === 0) {
    console.log("No source station photos found in", SOURCE_DIR);
    return;
  }

  let overBudget = 0;
  for (const source of sources) {
    const path = join(SOURCE_DIR, source.name);
    const base = basename(source.name, extname(source.name));
    console.log(`\n${source.name}:`);

    for (const width of WIDTHS) {
      for (const format of FORMATS) {
        const outName = `${base}-${width}w.${format}`;
        const outPath = join(OUTPUT_DIR, outName);
        const resized = sharp(path).resize({ width, withoutEnlargement: true });
        const buffer = await encode(resized, format);
        await sharp(buffer).toFile(outPath);
        const kb = (buffer.byteLength / 1024).toFixed(1);
        const flag = format === "avif" && width === 1280 && buffer.byteLength > AVIF_1280W_BUDGET_BYTES;
        if (flag) overBudget++;
        console.log(`  ${outName}: ${kb} KB${flag ? "  <-- OVER the 250KB 1280w AVIF budget" : ""}`);
      }
    }
  }

  if (overBudget > 0) {
    console.log(`\n${overBudget} file(s) exceed the 1280w AVIF budget — raise compression or revisit the source.`);
  }
}

main().catch((err: unknown) => {
  console.error(err);
  process.exitCode = 1;
});
