/**
 * Regenerates docs/BALANCE.md from the same harness validation/balance.test.ts asserts
 * against (packages/sim/src/engine/balance.ts), so the committed doc can never drift from
 * what CI actually checks. Run locally by the lead developer after any change that could
 * move the pass-rate distribution — a new incident, a retuned constant, a rebalanced bot.
 *
 * Usage:
 *   pnpm --filter @sol-keeper/sim run build   # this script runs against the built package
 *   node scripts/generate-balance-doc.ts
 */
import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
// A relative import to the built package, not the bare "@sol-keeper/sim" specifier: the
// package is only declared as a dependency of apps/web (workspace:*), and Node's ESM
// resolution for a bare specifier walks up from *this file's* location, not from the
// working directory a script happens to be run from — scripts/ itself has no node_modules
// entry for it. Still "the built package, not a source alias" (CLAUDE.md), just addressed
// directly rather than through a specifier only apps/web can resolve.
import {
  runCombination,
  decisionCoverage,
  idleBot,
  worstChoiceBot,
  greedyBot,
  prudentBot,
  type Bot,
  type MissionDifficulty,
  type ScenarioId,
} from "../packages/sim/dist/index.js";

const SEEDS = 150;
const SCENARIOS: readonly ScenarioId[] = ["jezero-outpost", "first-light", "the-long-night"];
const DIFFICULTIES: readonly MissionDifficulty[] = ["training", "nominal", "flightRated"];
const BOTS: readonly Bot[] = [idleBot, worstChoiceBot, greedyBot, prudentBot];

const OUT_PATH = fileURLToPath(new URL("../docs/BALANCE.md", import.meta.url));

function pct(x: number): string {
  return `${(x * 100).toFixed(1)}%`;
}

async function main(): Promise<void> {
  const rows: string[] = [];
  const allCauses = new Set<string>();
  const coverageSections: string[] = [];
  const t0 = Date.now();

  for (const scenarioId of SCENARIOS) {
    for (const difficulty of DIFFICULTIES) {
      for (const bot of BOTS) {
        const result = runCombination(scenarioId, difficulty, bot, SEEDS);
        for (const cause of result.causesSeen) allCauses.add(cause);
        const c = result.statusCounts;
        rows.push(
          `| ${scenarioId} | ${difficulty} | ${bot.id} | ${pct(result.successRate)} | ${c.success} | ${c.partial} | ${c.abort} | ${c.loss} | ${[...result.causesSeen].join(", ") || "—"} |`,
        );
      }
    }

    // M7.6 Part C.7: aggregated across all difficulties and bots for this scenario, so the
    // table stays a readable size — how often each incident response was ever chosen and the
    // fraction of runs that chose it that went on to succeed.
    const coverage = decisionCoverage(scenarioId, DIFFICULTIES, BOTS, SEEDS);
    const coverageRows = coverage
      .map((e) => `| ${e.incidentId} | ${e.responseId} | ${e.timesChosen} | ${pct(e.successRateWhenChosen)} |`)
      .join("\n");
    coverageSections.push(`### ${scenarioId}\n\n| Incident | Response | Times chosen | Success rate when chosen |\n|---|---|---|---|\n${coverageRows}`);
  }

  const md = `# Balance report

Generated by \`scripts/generate-balance-doc.ts\` from \`packages/sim/src/engine/balance.ts\` —
the same harness \`validation/balance.test.ts\` asserts the brief's pass/fail targets against
(docs/PHASE2_BRIEF.md, "Balance harness"). This file is generated output, never hand-edited:
regenerate it after any change that could move the distribution below, rather than editing
the numbers directly.

${SEEDS} seeds per row, computed in ${Date.now() - t0} ms.

## Brief targets

- idleBot success: <=5% (Nominal, Flight-Rated), <=30% (Training)
- prudentBot success: >=85% Training, >=70% Nominal, 40-60% Flight-Rated
- greedyBot: strictly between idleBot and prudentBot
- Every failure mode reachable in at least one idleBot or greedyBot seed

**Known gaps** (tracked in validation/balance.test.ts, not silently dropped — see that test
file's header comment for the full diagnosis): Jezero and The Long Night's prudentBot clears
every floor above but sits well past the Flight-Rated *upper* bound (its strategy neutralises
most incidents it responds to well enough that raising Flight-Rated's incident rate further
would only punish idleBot/greedyBot, not a skilled bot). First Light's prudentBot instead
misses the *lower* bound on every difficulty (\`depress-mir97\`'s fast kill clock, M7.8 Part A —
unrelated to the upper-bound gap above). idleBot's own Nominal ceiling (<=5%) is also missed
on First Light specifically, by a small margin.

## Outcome distribution

| Scenario | Difficulty | Bot | Success | success | partial | abort | loss | Causes seen |
|---|---|---|---|---|---|---|---|---|
${rows.join("\n")}

## Failure causes observed across every idleBot/greedyBot seed

${[...allCauses].sort().map((c) => `- \`${c}\``).join("\n")}

## Decision coverage (M7.6 Part C.7)

For each incident, how often every bot combined ever chose each response (across all three
difficulties, ${SEEDS} seeds each) and the fraction of those runs that went on to SUCCEED.
Correlation, not causation — a response chosen only in already-favourable runs would read
high without being the reason why (see \`DecisionCoverageEntry\`'s own doc comment,
packages/sim/src/engine/balance.ts) — read alongside the outcome table above, not in place
of it.

${coverageSections.join("\n\n")}
`;

  await writeFile(OUT_PATH, md, "utf8");
  console.log(`Wrote ${OUT_PATH}`);
}

await main();
